namespace EnterpriseAgentOs.Api.Database.Models;

/// <summary>
/// Type of a single entry in an agent's append-only activity log.
/// The dashboard renders different icons/colors per type.
/// </summary>
public enum AgentLogType
{
    ToolCall,
    ToolResult,
    MessageIn,
    MessageOut,
    ChannelIn,
    ChannelOut,
    System,
}

/// <summary>
/// Unified append-only event log for an agent. Replaces the legacy
/// AgentConversationRecord (chat messages) + AgentToolCallRecord (skill execution audit)
/// with a single ordered timeline the dashboard renders verbatim.
///
/// Send-message flow: dashboard mutation appends a <see cref="AgentLogType.MessageIn"/>
/// entry and kicks the agent pod. The agent appends <c>tool_call</c>, <c>tool_result</c>,
/// and <see cref="AgentLogType.MessageOut"/> entries as it runs. Clients subscribe to
/// <c>agentLogAppended</c> for live updates.
/// </summary>
public sealed class AgentLogRecord
{
    public Guid Id { get; init; } = Guid.NewGuid();

    public Guid AgentId { get; set; }
    public AgentRecord? Agent { get; set; }

    public DateTime Time { get; set; } = DateTime.UtcNow;

    public AgentLogType Type { get; set; }

    /// <summary>Skill action name for tool_call/tool_result. Null otherwise.</summary>
    [MaxLength(64)]
    public string? Tool { get; set; }

    /// <summary>Skill name (e.g. "github", "notion") for tool entries.</summary>
    [MaxLength(64)]
    public string? Integration { get; set; }

    /// <summary>Channel slug (e.g. "slack") for channel entries.</summary>
    [MaxLength(64)]
    public string? Channel { get; set; }

    /// <summary>
    /// For message/channel entries: the human-readable text.
    /// For tool_call: serialized JSON params.
    /// For tool_result: serialized JSON result or summary.
    /// For system: a short human-readable event description.
    /// </summary>
    public string Content { get; set; } = string.Empty;

    public int? DurationMs { get; set; }

    public int? InputTokens { get; set; }
    public int? OutputTokens { get; set; }

    /// <summary>
    /// Ties related entries together (e.g. a tool_call + its tool_result, or all entries
    /// generated by a single user message).
    /// </summary>
    [MaxLength(128)]
    public string? CorrelationId { get; set; }
}
