apiVersion: v2
name: enterprise-agent-os
description: Open-source infrastructure to scale AI agents.
type: application
version: 0.1.0
appVersion: "latest"
keywords:
  - ai-agents
  - agents
  - mcp
  - kubernetes
home: https://officeos.co
sources:
  - https://github.com/HarKro753/EnterpriseAgentOs
maintainers:
  - name: OfficeOS
    url: https://officeos.co

