namespace OffceOs.Domain.Features.Analytics;

/// <summary>
/// Type of a single entry in an agent's append-only activity log.
/// The dashboard renders different icons/colors per type.
/// </summary>
public enum AgentLogType
{
    ToolCall,
    ToolResult,
    MessageIn,
    MessageOut,
    ChannelIn,
    ChannelOut,
    System,
    AgentStartup,
    AgentShutdown,
    Error,
    ErrorPodConnection,
    ErrorLlmCall,
    ErrorToolExecution,
    ErrorSkillExecution,
    ErrorTurnOrchestration,
    ErrorMemory,
    ErrorConfiguration,
}

public sealed class AgentLogRecord
{
    public Guid Id { get; init; } = Guid.NewGuid();

    [MaxLength(64)]
    public string ResourceKind { get; init; } = ResourceLogKinds.Agent;

    public Guid? ResourceId { get; init; }

    [MaxLength(200)]
    public string? ResourceName { get; init; }

    [MaxLength(64)]
    public string? ParentResourceKind { get; init; }

    public Guid? ParentResourceId { get; init; }

    public Guid? AgentId { get; init; }
    public Guid? WorkspaceId { get; init; }
    public AgentRecord? Agent { get; init; }

    public DateTime Time { get; init; } = DateTime.UtcNow;

    public AgentLogType Type { get; init; }

    [MaxLength(16)]
    public string Severity { get; init; } = ResourceLogSeverityKinds.Info;

    /// <summary>Skill action name for tool_call/tool_result. Null otherwise.</summary>
    [MaxLength(64)]
    public string? Tool { get; init; }

    /// <summary>Skill name (e.g. "github", "notion") for tool entries.</summary>
    [MaxLength(64)]
    public string? Integration { get; init; }

    /// <summary>Channel slug (e.g. "slack") for channel entries.</summary>
    [MaxLength(64)]
    public string? Channel { get; init; }

    /// <summary>Concrete channel connection for channel entries, when known.</summary>
    public Guid? ChannelConnectionId { get; init; }

    /// <summary>
    /// For message/channel entries: the human-readable text.
    /// For tool_call: serialized JSON params.
    /// For tool_result: serialized JSON result or summary.
    /// For system: a short human-readable event description.
    /// </summary>
    public string Content { get; init; } = string.Empty;

    public TokenUsage Usage { get; init; } = TokenUsage.Empty;

    public string? MetadataJson { get; init; }

    /// <summary>
    /// Ties related entries together (e.g. a tool_call + its tool_result, or all entries
    /// generated by a single user message).
    /// </summary>
    [MaxLength(128)]
    public string? CorrelationId { get; init; }

    public Guid? RunId { get; init; }
    public Guid? ParentRunId { get; init; }

    // ── Factory methods ─────────────────────────────────────────────────────

    public static AgentLogRecord System(Guid agentId, string content, string? correlationId = null, DateTime? time = null, TokenUsage? usage = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.System, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow, Usage = usage ?? TokenUsage.Empty,
    };

    public static AgentLogRecord MessageIn(Guid agentId, string content, string? correlationId = null, DateTime? time = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.MessageIn, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static AgentLogRecord MessageOut(Guid agentId, string content, string? correlationId = null, DateTime? time = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.MessageOut, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static AgentLogRecord ToolCallEntry(Guid agentId, string toolName, string argsJson, string? correlationId = null, DateTime? time = null, string? integration = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.ToolCall, Tool = toolName, Integration = integration,
        Content = argsJson, CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static AgentLogRecord ToolResultEntry(Guid agentId, string toolName, string content, string? correlationId = null, DateTime? time = null, TokenUsage? usage = null, string? integration = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.ToolResult, Tool = toolName, Integration = integration,
        Content = content, CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
        Usage = usage ?? TokenUsage.Empty,
    };

    public static AgentLogRecord Error(Guid agentId, string content, string? correlationId = null, DateTime? time = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.Error, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static AgentLogRecord ChannelIn(Guid? agentId, string channel, string content, string? correlationId = null, Guid? channelConnectionId = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.ChannelIn, Channel = channel,
        ChannelConnectionId = channelConnectionId, Content = content, CorrelationId = correlationId,
    };

    public static AgentLogRecord ChannelOut(Guid agentId, string channel, string content, string? correlationId = null, Guid? channelConnectionId = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.ChannelOut, Channel = channel,
        ChannelConnectionId = channelConnectionId, Content = content, CorrelationId = correlationId,
    };
}

public static class ResourceLogKinds
{
    public const string Agent = "Agent";
    public const string Run = "Run";
    public const string Channel = "Channel";
    public const string IntegrationDeployment = "IntegrationDeployment";
    public const string Provider = "Provider";
}

public static class ResourceLogSeverityKinds
{
    public const string Debug = "debug";
    public const string Info = "info";
    public const string Warning = "warning";
    public const string Error = "error";
}
