import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export const metadata = {
	title: "Terms of Service — Office OS",
	description:
		"Terms and conditions for using the Office OS platform.",
};

export default function Terms() {
	return (
		<div className="min-h-screen bg-background text-primary font-sans">
			<nav className="sticky top-0 z-50 border-b border-border bg-background/80 backdrop-blur-md">
				<div className="mx-auto flex max-w-4xl items-center justify-between px-6 py-4">
					<Link
						href="/"
						className="flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"
					>
						<ArrowLeft className="h-4 w-4" />
						Back
					</Link>
					<span className="font-medium tracking-tight">Office OS</span>
					<div className="w-16" />
				</div>
			</nav>

			<main className="mx-auto max-w-4xl px-6 pt-20 pb-28 md:pt-28">
				<h1 className="text-4xl font-bold tracking-tight text-center md:text-5xl">
					Terms of Service
				</h1>
				<p className="mt-4 text-sm text-muted-foreground text-center">
					Last updated: April 13, 2026
				</p>

				<div className="mt-16 space-y-12 text-muted-foreground leading-relaxed">
					{/* Intro */}
					<section>
						<p>
							These Terms of Service (&quot;Terms&quot;) govern your use of the
							Office OS platform operated by Office OS GmbH
							(&quot;we&quot;, &quot;us&quot;, &quot;our&quot;). By creating an
							account or using the platform, you agree to these Terms.
						</p>
					</section>

					{/* Service Description */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							1. Service Description
						</h2>
						<p>
							Office OS is a Kubernetes-native platform for deploying and
							managing autonomous AI agents. The platform enables you to create
							agents, assign skills, manage credentials, and execute tasks
							through a central dashboard. Agents run as isolated pods on
							Kubernetes and interact with third-party services through skills
							and LLM providers you configure.
						</p>
					</section>

					{/* User Responsibility */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							2. User Responsibility
						</h2>
						<p>
							You are responsible for reviewing and validating all agent outputs
							before acting on them. Agents operate autonomously and may produce
							incorrect, incomplete, or unexpected results. You acknowledge that
							you are solely responsible for any decisions or actions taken
							based on agent outputs.
						</p>
						<p className="mt-3">
							You are responsible for the credentials you provide to the
							platform and for ensuring that your use of third-party services
							through agents complies with the respective service terms.
						</p>
					</section>

					{/* No Warranty on Agent Output */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							3. No Warranty on Agent Output
						</h2>
						<p>
							Agent outputs are generated by third-party LLM providers and
							executed through user-configured skills. All outputs are provided
							on a best-effort basis.{" "}
							<strong className="text-primary">
								We make no warranties, express or implied, regarding the
								accuracy, completeness, reliability, or fitness for any
								particular purpose of agent outputs.
							</strong>
						</p>
					</section>

					{/* Limitation of Liability */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							4. Limitation of Liability
						</h2>
						<p>
							To the maximum extent permitted by applicable law, Office OS GmbH
							shall not be liable for any indirect, incidental, special,
							consequential, or punitive damages arising from your use of the
							platform, including but not limited to damages caused by agent
							actions, skill executions, or LLM outputs.
						</p>
						<p className="mt-3">
							Our total liability for any claims arising from these Terms or
							your use of the platform shall not exceed the total amount you
							paid to us in the twelve (12) months preceding the claim.
						</p>
					</section>

					{/* Acceptable Use */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							5. Acceptable Use
						</h2>
						<p>You agree not to use Office OS to:</p>
						<ul className="mt-3 space-y-2 list-disc pl-5">
							<li>
								Engage in any illegal activity or violate applicable laws and
								regulations.
							</li>
							<li>
								Deploy agents that perform malicious actions, including
								unauthorized access to systems, data exfiltration, or
								distribution of malware.
							</li>
							<li>
								Generate or distribute harmful, abusive, or deceptive content.
							</li>
							<li>
								Circumvent platform security controls, rate limits, or access
								restrictions.
							</li>
							<li>
								Use the platform in a way that could harm other users or
								degrade service performance.
							</li>
						</ul>
					</section>

					{/* Account Termination */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							6. Account Termination
						</h2>
						<p>
							We reserve the right to suspend or terminate your account at any
							time if we reasonably believe you have violated these Terms or our
							Acceptable Use policy. We will make reasonable efforts to notify
							you before termination unless the violation poses an immediate
							risk. Upon termination, your agent data will be retained for 30
							days to allow for data export, then permanently deleted.
						</p>
					</section>

					{/* Enterprise SLAs */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							7. Enterprise Agreements
						</h2>
						<p>
							Enterprise customers may negotiate separate Service Level
							Agreements (SLAs) with specific uptime guarantees, support
							commitments, and custom terms. Enterprise SLAs, where applicable,
							take precedence over these public Terms of Service.
						</p>
						<p className="mt-3">
							A Data Processing Agreement (DPA) is available for enterprise
							customers upon request, covering GDPR-compliant data processing,
							sub-processor management, and data transfer safeguards.
						</p>
					</section>

					{/* Intellectual Property */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							8. Intellectual Property
						</h2>
						<p>
							You retain full ownership of your agent configurations, custom
							skills, workspace data, and any content generated through your use
							of the platform. We claim no intellectual property rights over
							your data or agent outputs.
						</p>
					</section>

					{/* Changes to Terms */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							9. Changes to Terms
						</h2>
						<p>
							We may update these Terms from time to time. Material changes will
							be communicated via email or through the platform dashboard at
							least 30 days before they take effect. Continued use of the
							platform after the effective date constitutes acceptance of the
							updated Terms.
						</p>
					</section>

					{/* Governing Law */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							10. Governing Law
						</h2>
						<p>
							These Terms are governed by and construed in accordance with the
							laws of the Federal Republic of Germany. Any disputes arising from
							these Terms shall be subject to the exclusive jurisdiction of the
							courts of Hamburg, Germany.
						</p>
					</section>

					{/* Contact */}
					<section>
						<h2 className="text-2xl font-bold tracking-tight text-primary mb-4">
							11. Contact
						</h2>
						<p>
							For questions about these Terms, contact us at{" "}
							<a
								href="mailto:legal@harrokrog.com"
								className="text-primary underline underline-offset-4 hover:text-primary/80"
							>
								legal@harrokrog.com
							</a>
							.
						</p>
					</section>
				</div>
			</main>

			<footer className="border-t border-border py-8 text-center text-sm text-muted-foreground">
				Made in Hamburg — &copy; 2026 Office OS GmbH
			</footer>
		</div>
	);
}
