namespace OffceOs.Domain.Features.Analytics;

/// <summary>
/// Type of a single entry in an agent's append-only activity log.
/// The dashboard renders different icons/colors per type.
/// </summary>
public enum AgentLogType
{
    ToolCall,
    ToolResult,
    MessageIn,
    MessageOut,
    ChannelIn,
    ChannelOut,
    System,
    AgentStartup,
    AgentShutdown,
    Error,
    ErrorPodConnection,
    ErrorLlmCall,
    ErrorToolExecution,
    ErrorSkillExecution,
    ErrorTurnOrchestration,
    ErrorMemory,
    ErrorConfiguration,
}

/// <summary>
/// Unified append-only event log for an agent. Replaces the legacy
/// AgentConversationRecord (chat messages) + AgentToolCallRecord (skill execution audit)
/// with a single ordered timeline the dashboard renders verbatim.
///
/// Send-message flow: dashboard mutation appends a <see cref="AgentLogType.MessageIn"/>
/// entry and kicks the agent pod. The agent appends <c>tool_call</c>, <c>tool_result</c>,
/// and <see cref="AgentLogType.MessageOut"/> entries as it runs. Clients subscribe to
/// <c>agentLogAppended</c> for live updates.
/// </summary>
public sealed class AgentLogRecord
{
    public Guid Id { get; init; } = Guid.NewGuid();

    public Guid? AgentId { get; init; }
    public Guid? WorkspaceId { get; init; }
    public AgentRecord? Agent { get; init; }

    public DateTime Time { get; init; } = DateTime.UtcNow;

    public AgentLogType Type { get; init; }

    /// <summary>Skill action name for tool_call/tool_result. Null otherwise.</summary>
    [MaxLength(64)]
    public string? Tool { get; init; }

    /// <summary>Skill name (e.g. "github", "notion") for tool entries.</summary>
    [MaxLength(64)]
    public string? Integration { get; init; }

    /// <summary>Channel slug (e.g. "slack") for channel entries.</summary>
    [MaxLength(64)]
    public string? Channel { get; init; }

    /// <summary>Concrete channel connection for channel entries, when known.</summary>
    public Guid? ChannelConnectionId { get; init; }

    /// <summary>
    /// For message/channel entries: the human-readable text.
    /// For tool_call: serialized JSON params.
    /// For tool_result: serialized JSON result or summary.
    /// For system: a short human-readable event description.
    /// </summary>
    public string Content { get; init; } = string.Empty;

    public TokenUsage Usage { get; init; } = TokenUsage.Empty;

    /// <summary>
    /// Ties related entries together (e.g. a tool_call + its tool_result, or all entries
    /// generated by a single user message).
    /// </summary>
    [MaxLength(128)]
    public string? CorrelationId { get; init; }

    public Guid? RunId { get; init; }
    public Guid? ParentRunId { get; init; }

    // ── Factory methods ─────────────────────────────────────────────────────

    public static AgentLogRecord System(Guid agentId, string content, string? correlationId = null, DateTime? time = null, TokenUsage? usage = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.System, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow, Usage = usage ?? TokenUsage.Empty,
    };

    public static AgentLogRecord MessageIn(Guid agentId, string content, string? correlationId = null, DateTime? time = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.MessageIn, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static AgentLogRecord MessageOut(Guid agentId, string content, string? correlationId = null, DateTime? time = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.MessageOut, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static AgentLogRecord ToolCallEntry(Guid agentId, string toolName, string argsJson, string? correlationId = null, DateTime? time = null, string? integration = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.ToolCall, Tool = toolName, Integration = integration,
        Content = argsJson, CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static AgentLogRecord ToolResultEntry(Guid agentId, string toolName, string content, string? correlationId = null, DateTime? time = null, TokenUsage? usage = null, string? integration = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.ToolResult, Tool = toolName, Integration = integration,
        Content = content, CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
        Usage = usage ?? TokenUsage.Empty,
    };

    public static AgentLogRecord Error(Guid agentId, string content, string? correlationId = null, DateTime? time = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.Error, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static AgentLogRecord ChannelIn(Guid? agentId, string channel, string content, string? correlationId = null, Guid? channelConnectionId = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.ChannelIn, Channel = channel,
        ChannelConnectionId = channelConnectionId, Content = content, CorrelationId = correlationId,
    };

    public static AgentLogRecord ChannelOut(Guid agentId, string channel, string content, string? correlationId = null, Guid? channelConnectionId = null) => new()
    {
        AgentId = agentId, Type = AgentLogType.ChannelOut, Channel = channel,
        ChannelConnectionId = channelConnectionId, Content = content, CorrelationId = correlationId,
    };
}
