namespace OffceOs.Domain.Features.ResourceLogs;

/// <summary>
/// Type of a single entry in an agent's append-only activity log.
/// The dashboard renders different icons/colors per type.
/// </summary>
public enum ResourceLogType
{
    ToolCall,
    ToolResult,
    MessageIn,
    MessageOut,
    ChannelIn,
    ChannelOut,
    System,
    AgentStartup,
    AgentShutdown,
    ModelCall,
    Error,
    ErrorPodConnection,
    ErrorLlmCall,
    ErrorToolExecution,
    ErrorSkillExecution,
    ErrorTurnOrchestration,
    ErrorMemory,
    ErrorConfiguration,
}

public sealed class ResourceLogRecord
{
    public Guid Id { get; init; } = Guid.NewGuid();

    [MaxLength(64)]
    public string ResourceKind { get; init; } = ResourceLogKinds.Agent;

    public Guid? ResourceId { get; init; }

    [MaxLength(200)]
    public string? ResourceName { get; init; }

    [MaxLength(64)]
    public string? ParentResourceKind { get; init; }

    public Guid? ParentResourceId { get; init; }

    public Guid? AgentId { get; init; }
    public Guid? WorkspaceId { get; init; }
    public AgentRecord? Agent { get; init; }

    public DateTime Time { get; init; } = DateTime.UtcNow;

    public ResourceLogType Type { get; init; }

    [MaxLength(16)]
    public string Severity { get; init; } = ResourceLogSeverityKinds.Info;

    /// <summary>Skill action name for tool_call/tool_result. Null otherwise.</summary>
    [MaxLength(64)]
    public string? Tool { get; init; }

    /// <summary>Skill name (e.g. "github", "notion") for tool entries.</summary>
    [MaxLength(64)]
    public string? Integration { get; init; }

    /// <summary>Channel slug (e.g. "slack") for channel entries.</summary>
    [MaxLength(64)]
    public string? Channel { get; init; }

    /// <summary>Concrete channel connection for channel entries, when known.</summary>
    public Guid? ChannelConnectionId { get; init; }

    /// <summary>
    /// For message/channel entries: the human-readable text.
    /// For tool_call: serialized JSON params.
    /// For tool_result: serialized JSON result or summary.
    /// For system: a short human-readable event description.
    /// </summary>
    public string Content { get; init; } = string.Empty;

    public TokenUsage Usage { get; init; } = TokenUsage.Empty;

    public string? MetadataJson { get; init; }

    /// <summary>
    /// Ties related entries together (e.g. a tool_call + its tool_result, or all entries
    /// generated by a single user message).
    /// </summary>
    [MaxLength(128)]
    public string? CorrelationId { get; init; }

    [MaxLength(32)]
    public string? WorkStatus { get; init; }

    [MaxLength(32)]
    public string? WorkPurpose { get; init; }

    public Guid? DefinitionId { get; init; }
    public DateTime? StartedAt { get; init; }
    public DateTime? CompletedAt { get; init; }
    public string? WorkError { get; init; }

    // ── Factory methods ─────────────────────────────────────────────────────

    public static ResourceLogRecord System(Guid agentId, string content, string? correlationId = null, DateTime? time = null, TokenUsage? usage = null) => new()
    {
        AgentId = agentId, Type = ResourceLogType.System, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow, Usage = usage ?? TokenUsage.Empty,
    };

    public static ResourceLogRecord MessageIn(Guid agentId, string content, string? correlationId = null, DateTime? time = null) => new()
    {
        AgentId = agentId, Type = ResourceLogType.MessageIn, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static ResourceLogRecord MessageOut(Guid agentId, string content, string? correlationId = null, DateTime? time = null) => new()
    {
        AgentId = agentId, Type = ResourceLogType.MessageOut, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static ResourceLogRecord ToolCallEntry(Guid agentId, string toolName, string argsJson, string? correlationId = null, DateTime? time = null, string? integration = null) => new()
    {
        AgentId = agentId, Type = ResourceLogType.ToolCall, Tool = toolName, Integration = integration,
        Content = argsJson, CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static ResourceLogRecord ToolResultEntry(Guid agentId, string toolName, string content, string? correlationId = null, DateTime? time = null, TokenUsage? usage = null, string? integration = null) => new()
    {
        AgentId = agentId, Type = ResourceLogType.ToolResult, Tool = toolName, Integration = integration,
        Content = content, CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
        Usage = usage ?? TokenUsage.Empty,
    };

    public static ResourceLogRecord Error(Guid agentId, string content, string? correlationId = null, DateTime? time = null) => new()
    {
        AgentId = agentId, Type = ResourceLogType.Error, Content = content,
        CorrelationId = correlationId, Time = time ?? DateTime.UtcNow,
    };

    public static ResourceLogRecord ChannelIn(Guid? agentId, string channel, string content, string? correlationId = null, Guid? channelConnectionId = null) => new()
    {
        AgentId = agentId, Type = ResourceLogType.ChannelIn, Channel = channel,
        ChannelConnectionId = channelConnectionId, Content = content, CorrelationId = correlationId,
    };

    public static ResourceLogRecord ChannelOut(Guid agentId, string channel, string content, string? correlationId = null, Guid? channelConnectionId = null) => new()
    {
        AgentId = agentId, Type = ResourceLogType.ChannelOut, Channel = channel,
        ChannelConnectionId = channelConnectionId, Content = content, CorrelationId = correlationId,
    };
}

public static class ResourceLogKinds
{
    public const string Agent = "Agent";
    public const string Browser = "Browser";
    public const string Channel = "Channel";
    public const string ControlPlane = "ControlPlane";
    public const string Credential = "Credential";
    public const string IntegrationDeployment = "IntegrationDeployment";
    public const string MemoryStore = "MemoryStore";
    public const string Model = "Model";
    public const string Provider = "Provider";
    public const string Routine = "Routine";
    public const string Workspace = "Workspace";
    public const string WorkspaceBinding = "WorkspaceBinding";
}

public static class ResourceLogSeverityKinds
{
    public const string Debug = "debug";
    public const string Info = "info";
    public const string Warning = "warning";
    public const string Error = "error";
}
