using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace EnterpriseAgentOs.Application.Features.Mcp;

public static class McpServerSeeder
{
    private const string BrandfetchClientIdEnvironmentVariable = "BRANDFETCH_CLIENT_ID";
    private const string BrandfetchClientIdPlaceholder = "BRANDFETCH_CLIENT_ID";

    public static async Task SeedAsync(IServiceProvider services)
    {
        var repo = services.GetRequiredService<IMcpServerRepository>();
        var logger = services.GetRequiredService<ILogger<McpServerService>>();

        if (string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable(BrandfetchClientIdEnvironmentVariable)))
        {
            logger.LogWarning(
                "{EnvironmentVariable} is not set; built-in MCP logo URLs will use the Brandfetch client ID placeholder",
                BrandfetchClientIdEnvironmentVariable);
        }

        var servers = GetBuiltinServers();
        foreach (var server in servers)
        {
            await repo.UpsertAsync(server);
        }

        logger.LogInformation("Seeded {Count} built-in MCP servers", servers.Count);
    }

    private static string BrandfetchLogo(string domain, string alt)
    {
        var clientId = Environment.GetEnvironmentVariable(BrandfetchClientIdEnvironmentVariable);
        var clientIdQuery = string.IsNullOrWhiteSpace(clientId)
            ? BrandfetchClientIdPlaceholder
            : Uri.EscapeDataString(clientId);
        var encodedDomain = Uri.EscapeDataString(domain);
        var encodedAlt = System.Net.WebUtility.HtmlEncode($"{alt} logo");

        return $"""<img src="https://cdn.brandfetch.io/{encodedDomain}/symbol.svg?c={clientIdQuery}" alt="{encodedAlt}" loading="lazy" decoding="async" referrerpolicy="no-referrer" />""";
    }

    private static List<McpServerRecord> GetBuiltinServers() =>
    [
        // ── Developer Tools ─────────────────────────────────────────────

        new()
        {
            Name = "github",
            Title = "GitHub",
            Description = "Full-featured GitHub integration that lets agents manage repositories, issues, pull requests, code search, file operations, and branch management. Supports creating and updating files, pushing commits, searching across codebases, and automating common GitHub workflows — all through the Model Context Protocol.",
            Subtitle = "Manage repositories, issues, and pull requests from any conversation",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("github.com", "GitHub"),
            ToolsJson = """[{"name":"create_or_update_file","description":"Create or update a file in a repository"},{"name":"search_repositories","description":"Search for GitHub repositories"},{"name":"create_repository","description":"Create a new repository"},{"name":"get_file_contents","description":"Get contents of a file"},{"name":"push_files","description":"Push multiple files in a single commit"},{"name":"create_issue","description":"Create a new issue"},{"name":"create_pull_request","description":"Create a pull request"},{"name":"list_issues","description":"List issues in a repository"},{"name":"update_issue","description":"Update an existing issue"},{"name":"add_issue_comment","description":"Add a comment to an issue"},{"name":"search_code","description":"Search code across repositories"},{"name":"create_branch","description":"Create a new branch"},{"name":"list_commits","description":"List commits in a repository"},{"name":"get_issue","description":"Get details of an issue"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-github"]""",
            Category = "developer",
            CredentialFieldsJson = """[{"name":"GITHUB_PERSONAL_ACCESS_TOKEN","label":"Personal Access Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "gitlab",
            Title = "GitLab",
            Description = "Comprehensive GitLab integration for managing repositories, merge requests, issues, and CI/CD pipelines. Agents can create and review merge requests, manage project issues, trigger pipelines, and navigate GitLab's project structure. Supports both gitlab.com and self-hosted GitLab instances.",
            Subtitle = "Manage repos, merge requests, and CI/CD pipelines on GitLab",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("gitlab.com", "GitLab"),
            ToolsJson = """[{"name":"create_merge_request","description":"Create a new merge request"},{"name":"list_merge_requests","description":"List merge requests"},{"name":"get_project","description":"Get project details"},{"name":"list_issues","description":"List project issues"},{"name":"create_issue","description":"Create a new issue"},{"name":"get_file_contents","description":"Get file contents from a repository"},{"name":"list_pipelines","description":"List CI/CD pipelines"},{"name":"create_branch","description":"Create a new branch"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-gitlab"]""",
            Category = "developer",
            CredentialFieldsJson = """[{"name":"GITLAB_PERSONAL_ACCESS_TOKEN","label":"Personal Access Token","type":"password","required":true},{"name":"GITLAB_API_URL","label":"GitLab API URL","type":"text","required":false}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "git",
            Title = "Git",
            Description = "Direct access to local Git repositories for reading history, diffs, and making commits. Agents can check status, stage changes, create branches, view logs, and perform all standard Git operations without needing shell access. Ideal for code review and version control automation.",
            Subtitle = "Read, search, and manipulate local Git repositories",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/git",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("git-scm.com", "Git"),
            ToolsJson = """[{"name":"git_status","description":"Show working tree status"},{"name":"git_diff_unstaged","description":"Show unstaged changes"},{"name":"git_diff_staged","description":"Show staged changes"},{"name":"git_commit","description":"Create a commit"},{"name":"git_add","description":"Stage files"},{"name":"git_reset","description":"Unstage files"},{"name":"git_log","description":"View commit history"},{"name":"git_create_branch","description":"Create a new branch"},{"name":"git_checkout","description":"Switch branches"},{"name":"git_show","description":"Show commit details"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-git"]""",
            Category = "developer",
            IsBuiltin = true,
        },
        new()
        {
            Name = "filesystem",
            Title = "Filesystem",
            Description = "Secure file system operations with configurable access controls and sandboxing. Agents can read, write, edit, and search files, create directories, and navigate file trees. Access is restricted to explicitly allowed directories, making it safe for production use.",
            Subtitle = "Secure file operations with configurable access controls",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("modelcontextprotocol.io", "Filesystem"),
            ToolsJson = """[{"name":"read_file","description":"Read contents of a file"},{"name":"read_multiple_files","description":"Read multiple files at once"},{"name":"write_file","description":"Write content to a file"},{"name":"edit_file","description":"Edit a file with search/replace"},{"name":"create_directory","description":"Create a directory"},{"name":"list_directory","description":"List directory contents"},{"name":"directory_tree","description":"Get recursive directory tree"},{"name":"move_file","description":"Move or rename a file"},{"name":"search_files","description":"Search for files by pattern"},{"name":"get_file_info","description":"Get file metadata"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-filesystem","/home"]""",
            Category = "developer",
            IsBuiltin = true,
        },
        new()
        {
            Name = "playwright",
            Title = "Playwright",
            Description = "Browser automation powered by Microsoft Playwright for end-to-end testing and web interaction. Agents can navigate pages, click elements, fill forms, take screenshots, and execute JavaScript in real browser contexts. Supports Chromium, Firefox, and WebKit.",
            Subtitle = "Automate browsers for testing, scraping, and web interaction",
            AuthorName = "Microsoft",
            AuthorUrl = "https://github.com/microsoft",
            DocumentationUrl = "https://github.com/microsoft/playwright-mcp",
            RepositoryUrl = "https://github.com/microsoft/playwright-mcp",
            Logo = BrandfetchLogo("playwright.dev", "Playwright"),
            ToolsJson = """[{"name":"browser_navigate","description":"Navigate to a URL"},{"name":"browser_screenshot","description":"Take a screenshot"},{"name":"browser_click","description":"Click an element"},{"name":"browser_fill","description":"Fill in a form field"},{"name":"browser_select","description":"Select an option"},{"name":"browser_hover","description":"Hover over an element"},{"name":"browser_evaluate","description":"Execute JavaScript in the browser"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@playwright/mcp@latest"]""",
            Category = "developer",
            IsBuiltin = true,
        },
        new()
        {
            Name = "sentry",
            Title = "Sentry",
            Description = "Access Sentry error tracking and performance monitoring data. Agents can search for issues, view error details with stack traces, analyze crash reports, and monitor application health. Helps with debugging production issues by surfacing relevant error context directly in conversations.",
            Subtitle = "Debug production errors with stack traces and crash reports",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/sentry",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("sentry.io", "Sentry"),
            ToolsJson = """[{"name":"list_issues","description":"List Sentry issues"},{"name":"get_issue","description":"Get issue details"},{"name":"list_events","description":"List events for an issue"},{"name":"get_event","description":"Get event details with stack trace"},{"name":"list_projects","description":"List Sentry projects"},{"name":"search_issues","description":"Search issues by query"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-sentry"]""",
            Category = "developer",
            CredentialFieldsJson = """[{"name":"SENTRY_AUTH_TOKEN","label":"Auth Token","type":"password","required":true},{"name":"SENTRY_ORG","label":"Organization Slug","type":"text","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "linear",
            Title = "Linear",
            Description = "Manage Linear project tracking directly from conversations. Agents can create, update, and search issues, manage projects and cycles, assign team members, and track progress. Ideal for engineering teams that use Linear for sprint planning and issue management.",
            Subtitle = "Track issues, projects, and sprints in Linear",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/jerhadf/linear-mcp-server",
            RepositoryUrl = "https://github.com/jerhadf/linear-mcp-server",
            Logo = BrandfetchLogo("linear.app", "Linear"),
            ToolsJson = """[{"name":"create_issue","description":"Create a new Linear issue"},{"name":"update_issue","description":"Update an existing issue"},{"name":"search_issues","description":"Search for issues"},{"name":"list_projects","description":"List projects"},{"name":"list_teams","description":"List teams"},{"name":"get_issue","description":"Get issue details"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-linear"]""",
            Category = "developer",
            CredentialFieldsJson = """[{"name":"LINEAR_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "jira",
            Title = "Jira",
            Description = "Search, create, and manage Jira issues and projects through the Atlassian API. Agents can create tickets, transition issue statuses, add comments, search with JQL, and manage sprints. Supports both Jira Cloud and Jira Data Center deployments.",
            Subtitle = "Search, create, and manage issues across Jira projects",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/sooperset/mcp-atlassian",
            RepositoryUrl = "https://github.com/sooperset/mcp-atlassian",
            Logo = BrandfetchLogo("atlassian.com", "Jira"),
            ToolsJson = """[{"name":"search_issues","description":"Search issues with JQL"},{"name":"create_issue","description":"Create a new Jira issue"},{"name":"update_issue","description":"Update an existing issue"},{"name":"get_issue","description":"Get issue details"},{"name":"add_comment","description":"Add a comment to an issue"},{"name":"transition_issue","description":"Transition issue status"},{"name":"list_projects","description":"List Jira projects"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-jira"]""",
            Category = "developer",
            CredentialFieldsJson = """[{"name":"JIRA_URL","label":"Jira URL","type":"text","required":true},{"name":"JIRA_EMAIL","label":"Email","type":"text","required":true},{"name":"JIRA_API_TOKEN","label":"API Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "postman",
            Title = "Postman",
            Description = "Access and manage Postman collections, environments, and APIs. Agents can explore API definitions, run collection requests, manage environment variables, and navigate workspace resources. Perfect for API development, testing, and documentation workflows.",
            Subtitle = "Explore and test APIs with Postman collections",
            AuthorName = "Postman",
            AuthorUrl = "https://www.postman.com",
            DocumentationUrl = "https://github.com/postmanlabs/postman-mcp-server",
            RepositoryUrl = "https://github.com/postmanlabs/postman-mcp-server",
            Logo = BrandfetchLogo("postman.com", "Postman"),
            ToolsJson = """[{"name":"list_collections","description":"List Postman collections"},{"name":"get_collection","description":"Get collection details"},{"name":"list_environments","description":"List environments"},{"name":"get_environment","description":"Get environment variables"},{"name":"list_workspaces","description":"List workspaces"},{"name":"run_request","description":"Run a collection request"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@postman/mcp-server"]""",
            Category = "developer",
            CredentialFieldsJson = """[{"name":"POSTMAN_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },

        // ── Databases ───────────────────────────────────────────────────

        new()
        {
            Name = "postgres",
            Title = "PostgreSQL",
            Description = "Query and manage PostgreSQL databases with full SQL support. Agents can run queries, list tables, describe schemas, and explore database structure. Provides read-only access by default for safety, with optional write access. Ideal for data analysis, schema exploration, and report generation.",
            Subtitle = "Query, explore, and manage PostgreSQL databases",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("postgresql.org", "PostgreSQL"),
            ToolsJson = """[{"name":"query","description":"Run a SQL query"},{"name":"list_tables","description":"List all tables"},{"name":"describe_table","description":"Describe table schema"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-postgres"]""",
            Category = "database",
            CredentialFieldsJson = """[{"name":"POSTGRES_CONNECTION_STRING","label":"Connection String","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "sqlite",
            Title = "SQLite",
            Description = "Query and manage SQLite databases with built-in analysis and insight tracking. Agents can run read and write queries, create tables, explore schemas, and automatically track analytical insights. Perfect for local data analysis, prototyping, and embedded database workflows.",
            Subtitle = "Lightweight SQL database with built-in analysis",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("sqlite.org", "SQLite"),
            ToolsJson = """[{"name":"read_query","description":"Run a SELECT query"},{"name":"write_query","description":"Run an INSERT/UPDATE/DELETE query"},{"name":"create_table","description":"Create a new table"},{"name":"list_tables","description":"List all tables"},{"name":"describe_table","description":"Describe table schema"},{"name":"append_insight","description":"Save an analytical insight"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "uvx",
            Args = """["mcp-server-sqlite"]""",
            Category = "database",
            IsBuiltin = true,
        },
        new()
        {
            Name = "redis",
            Title = "Redis",
            Description = "Interact with Redis key-value stores for caching, session management, and real-time data operations. Agents can get and set keys, delete entries, list keys by pattern, and inspect server information. Useful for debugging cache issues and managing application state.",
            Subtitle = "Fast key-value operations for caching and real-time data",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/redis",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("redis.io", "Redis"),
            ToolsJson = """[{"name":"get","description":"Get a key value"},{"name":"set","description":"Set a key value"},{"name":"delete","description":"Delete a key"},{"name":"list_keys","description":"List keys by pattern"},{"name":"info","description":"Get Redis server info"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-redis"]""",
            Category = "database",
            CredentialFieldsJson = """[{"name":"REDIS_URL","label":"Redis URL","type":"text","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "mysql",
            Title = "MySQL",
            Description = "Query and manage MySQL databases with full SQL support. Agents can execute queries, list tables, describe schemas, and explore database structure. Supports authentication with standard MySQL credentials and works with MySQL 5.7+ and MariaDB.",
            Subtitle = "Query, explore, and manage MySQL databases",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/benborla/mcp-server-mysql",
            RepositoryUrl = "https://github.com/benborla/mcp-server-mysql",
            Logo = BrandfetchLogo("mysql.com", "MySQL"),
            ToolsJson = """[{"name":"query","description":"Run a SQL query"},{"name":"list_tables","description":"List all tables"},{"name":"describe_table","description":"Describe table schema"},{"name":"list_databases","description":"List available databases"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-mysql"]""",
            Category = "database",
            CredentialFieldsJson = """[{"name":"MYSQL_HOST","label":"Host","type":"text","required":true},{"name":"MYSQL_USER","label":"User","type":"text","required":true},{"name":"MYSQL_PASSWORD","label":"Password","type":"password","required":true},{"name":"MYSQL_DATABASE","label":"Database","type":"text","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "mongodb",
            Title = "MongoDB",
            Description = "Query and manage MongoDB databases and collections. Agents can run aggregation pipelines, find documents, insert and update records, list collections, and explore document schemas. Supports MongoDB Atlas and self-hosted deployments with standard connection URIs.",
            Subtitle = "Query documents and manage MongoDB collections",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/kiliczsh/mcp-mongo-server",
            RepositoryUrl = "https://github.com/kiliczsh/mcp-mongo-server",
            Logo = BrandfetchLogo("mongodb.com", "MongoDB"),
            ToolsJson = """[{"name":"find","description":"Find documents in a collection"},{"name":"insert_one","description":"Insert a document"},{"name":"update_one","description":"Update a document"},{"name":"aggregate","description":"Run an aggregation pipeline"},{"name":"list_collections","description":"List collections"},{"name":"count_documents","description":"Count matching documents"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-mongodb"]""",
            Category = "database",
            CredentialFieldsJson = """[{"name":"MONGODB_URI","label":"Connection URI","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "supabase",
            Title = "Supabase",
            Description = "Manage Supabase projects including Postgres databases, authentication, storage buckets, and edge functions. Agents can run SQL queries, manage users, upload files, and deploy serverless functions. A complete backend-as-a-service integration for rapid application development.",
            Subtitle = "Postgres, auth, storage, and edge functions in one platform",
            AuthorName = "Supabase",
            AuthorUrl = "https://supabase.com",
            DocumentationUrl = "https://github.com/supabase-community/supabase-mcp",
            RepositoryUrl = "https://github.com/supabase-community/supabase-mcp",
            Logo = BrandfetchLogo("supabase.com", "Supabase"),
            ToolsJson = """[{"name":"query","description":"Run a SQL query"},{"name":"list_tables","description":"List database tables"},{"name":"manage_users","description":"Manage auth users"},{"name":"list_buckets","description":"List storage buckets"},{"name":"upload_file","description":"Upload a file to storage"},{"name":"deploy_function","description":"Deploy an edge function"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@supabase/mcp-server-supabase@latest"]""",
            Category = "database",
            CredentialFieldsJson = """[{"name":"SUPABASE_ACCESS_TOKEN","label":"Access Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "neo4j",
            Title = "Neo4j",
            Description = "Query and explore Neo4j graph databases using Cypher. Agents can traverse relationships, find patterns, create nodes and edges, and visualize graph structures. Ideal for knowledge graphs, recommendation engines, fraud detection, and any domain with highly connected data.",
            Subtitle = "Explore and query graph databases with Cypher",
            AuthorName = "Neo4j",
            AuthorUrl = "https://neo4j.com",
            DocumentationUrl = "https://github.com/neo4j-contrib/mcp-neo4j",
            RepositoryUrl = "https://github.com/neo4j-contrib/mcp-neo4j",
            Logo = BrandfetchLogo("neo4j.com", "Neo4j"),
            ToolsJson = """[{"name":"cypher_query","description":"Run a Cypher query"},{"name":"get_schema","description":"Get database schema"},{"name":"create_node","description":"Create a node"},{"name":"create_relationship","description":"Create a relationship"},{"name":"search_nodes","description":"Search for nodes"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@neo4j/mcp-neo4j"]""",
            Category = "database",
            CredentialFieldsJson = """[{"name":"NEO4J_URI","label":"URI","type":"text","required":true},{"name":"NEO4J_USERNAME","label":"Username","type":"text","required":true},{"name":"NEO4J_PASSWORD","label":"Password","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "qdrant",
            Title = "Qdrant",
            Description = "Semantic memory and vector search powered by Qdrant. Agents can store and retrieve information using embeddings, enabling long-term memory, semantic similarity search, and retrieval-augmented generation. Supports filtering, payload storage, and collection management.",
            Subtitle = "Vector search and semantic memory for AI agents",
            AuthorName = "Qdrant",
            AuthorUrl = "https://qdrant.tech",
            DocumentationUrl = "https://github.com/qdrant/mcp-server-qdrant",
            RepositoryUrl = "https://github.com/qdrant/mcp-server-qdrant",
            Logo = BrandfetchLogo("qdrant.tech", "Qdrant"),
            ToolsJson = """[{"name":"store","description":"Store information with embeddings"},{"name":"search","description":"Semantic similarity search"},{"name":"delete","description":"Delete stored entries"},{"name":"list_collections","description":"List vector collections"},{"name":"create_collection","description":"Create a new collection"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "uvx",
            Args = """["mcp-server-qdrant"]""",
            Category = "database",
            CredentialFieldsJson = """[{"name":"QDRANT_URL","label":"Qdrant URL","type":"text","required":true},{"name":"QDRANT_API_KEY","label":"API Key","type":"password","required":false}]""",
            IsBuiltin = true,
        },

        // ── Search & Web ────────────────────────────────────────────────

        new()
        {
            Name = "brave-search",
            Title = "Brave Search",
            Description = "Search the web using the Brave Search API with privacy-focused results. Agents can perform web searches and local business searches, getting clean results without tracking. Supports filtering by freshness, region, and content type for precise information retrieval.",
            Subtitle = "Privacy-focused web and local search powered by Brave",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("brave.com", "Brave Search"),
            ToolsJson = """[{"name":"brave_web_search","description":"Search the web"},{"name":"brave_local_search","description":"Search for local businesses"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-brave-search"]""",
            Category = "search",
            CredentialFieldsJson = """[{"name":"BRAVE_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "exa",
            Title = "Exa",
            Description = "AI-native search engine that understands meaning, not just keywords. Agents can find content by describing what they want, discover similar pages, get direct answers, and retrieve full page contents. Built specifically for AI agents and retrieval-augmented generation workflows.",
            Subtitle = "AI-native search that understands meaning, not just keywords",
            AuthorName = "Exa",
            AuthorUrl = "https://exa.ai",
            DocumentationUrl = "https://github.com/exa-labs/exa-mcp-server",
            RepositoryUrl = "https://github.com/exa-labs/exa-mcp-server",
            Logo = BrandfetchLogo("exa.ai", "Exa"),
            ToolsJson = """[{"name":"search","description":"Search for content by meaning"},{"name":"find_similar","description":"Find similar pages"},{"name":"get_contents","description":"Get page contents"},{"name":"answer","description":"Get a direct answer"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","exa-mcp-server"]""",
            Category = "search",
            CredentialFieldsJson = """[{"name":"EXA_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "tavily",
            Title = "Tavily",
            Description = "AI-optimized search engine designed specifically for AI agents and retrieval-augmented generation. Returns clean, structured results with extracted content, eliminating the need for additional scraping. Supports domain filtering, search depth control, and content extraction.",
            Subtitle = "AI-optimized search engine built for agents and RAG",
            AuthorName = "Tavily",
            AuthorUrl = "https://tavily.com",
            DocumentationUrl = "https://github.com/tavily-ai/tavily-mcp",
            RepositoryUrl = "https://github.com/tavily-ai/tavily-mcp",
            Logo = BrandfetchLogo("tavily.com", "Tavily"),
            ToolsJson = """[{"name":"search","description":"Search the web with AI-optimized results"},{"name":"extract","description":"Extract content from URLs"},{"name":"search_context","description":"Search with context for RAG"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","tavily-mcp@latest"]""",
            Category = "search",
            CredentialFieldsJson = """[{"name":"TAVILY_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "fetch",
            Title = "Web Fetch",
            Description = "Fetch and convert web content for efficient LLM consumption. Retrieves web pages, converts HTML to clean markdown, and handles various content types including JSON and plain text. Supports custom headers, request methods, and content extraction for optimal token efficiency.",
            Subtitle = "Fetch web pages and convert them to clean markdown",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("modelcontextprotocol.io", "Web Fetch"),
            ToolsJson = """[{"name":"fetch","description":"Fetch a URL and return content"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-fetch"]""",
            Category = "search",
            IsBuiltin = true,
        },
        new()
        {
            Name = "firecrawl",
            Title = "Firecrawl",
            Description = "Advanced web scraping and crawling that extracts structured data from any website. Agents can scrape single pages, crawl entire sites, extract specific data fields, and convert web content to clean markdown. Handles JavaScript-rendered pages, anti-bot protection, and complex site structures.",
            Subtitle = "Scrape and crawl websites into structured, clean data",
            AuthorName = "Firecrawl",
            AuthorUrl = "https://firecrawl.dev",
            DocumentationUrl = "https://github.com/mendableai/firecrawl-mcp-server",
            RepositoryUrl = "https://github.com/mendableai/firecrawl-mcp-server",
            Logo = BrandfetchLogo("firecrawl.dev", "Firecrawl"),
            ToolsJson = """[{"name":"scrape","description":"Scrape a single page"},{"name":"crawl","description":"Crawl an entire website"},{"name":"map","description":"Map a website structure"},{"name":"extract","description":"Extract structured data from a page"},{"name":"search","description":"Search and scrape results"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","firecrawl-mcp"]""",
            Category = "search",
            CredentialFieldsJson = """[{"name":"FIRECRAWL_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "perplexity",
            Title = "Perplexity",
            Description = "Real-time web research powered by Perplexity AI's language models. Agents can ask questions and receive well-sourced, up-to-date answers synthesized from web sources. Ideal for fact-checking, research, and getting current information that may not be in the model's training data.",
            Subtitle = "Real-time web research with sourced, up-to-date answers",
            AuthorName = "Perplexity AI",
            AuthorUrl = "https://perplexity.ai",
            DocumentationUrl = "https://github.com/ppl-ai/modelcontextprotocol",
            RepositoryUrl = "https://github.com/ppl-ai/modelcontextprotocol",
            Logo = BrandfetchLogo("perplexity.ai", "Perplexity"),
            ToolsJson = """[{"name":"search","description":"Search the web with AI-synthesized answers"},{"name":"ask","description":"Ask a question with sourced answers"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@anthropic-ai/perplexity-mcp-server"]""",
            Category = "search",
            CredentialFieldsJson = """[{"name":"PERPLEXITY_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },

        // ── Communication ───────────────────────────────────────────────

        new()
        {
            Name = "slack",
            Title = "Slack",
            Description = "Full Slack workspace integration for reading and sending messages, managing channels, and interacting with threads. Agents can list channels, post messages, reply to threads, add reactions, view channel history, and look up user profiles. Enables conversational workflows across your team.",
            Subtitle = "Send messages, manage channels, and automate Slack workflows",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("slack.com", "Slack"),
            ToolsJson = """[{"name":"list_channels","description":"List workspace channels"},{"name":"post_message","description":"Post a message to a channel"},{"name":"reply_to_thread","description":"Reply to a thread"},{"name":"add_reaction","description":"Add an emoji reaction"},{"name":"get_channel_history","description":"Get channel message history"},{"name":"get_thread_replies","description":"Get thread replies"},{"name":"get_users","description":"List workspace users"},{"name":"get_user_profile","description":"Get a user profile"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-slack"]""",
            Category = "communication",
            CredentialFieldsJson = """[{"name":"SLACK_BOT_TOKEN","label":"Bot Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "gmail",
            Title = "Gmail",
            Description = "Read, search, and send emails via Gmail using OAuth authentication. Agents can compose and send emails, search the inbox with Gmail query syntax, read message contents, and manage labels. Provides secure access to Gmail without storing passwords.",
            Subtitle = "Read, search, and send emails through Gmail",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/gmail",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("gmail.com", "Gmail"),
            ToolsJson = """[{"name":"send_email","description":"Send an email"},{"name":"search_emails","description":"Search emails with Gmail query"},{"name":"read_email","description":"Read email contents"},{"name":"list_labels","description":"List Gmail labels"},{"name":"draft_email","description":"Create a draft email"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@anthropic-ai/gmail-mcp-server"]""",
            Category = "communication",
            CredentialFieldsJson = """[{"name":"GOOGLE_CLIENT_ID","label":"OAuth Client ID","type":"text","required":true},{"name":"GOOGLE_CLIENT_SECRET","label":"OAuth Client Secret","type":"password","required":true},{"name":"GOOGLE_REFRESH_TOKEN","label":"Refresh Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "email",
            Title = "Email (IMAP/SMTP)",
            Description = "Read and send emails via any standard IMAP/SMTP mail server. Works with any email provider that supports IMAP and SMTP protocols, including corporate Exchange servers, self-hosted mail, and consumer providers. Agents can read inbox messages, search mail, and compose replies.",
            Subtitle = "Read and send email via any IMAP/SMTP mail server",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/Shy2593666979/mcp-server-email",
            RepositoryUrl = "https://github.com/Shy2593666979/mcp-server-email",
            Logo = null,
            ToolsJson = """[{"name":"read_inbox","description":"Read inbox messages"},{"name":"send_email","description":"Send an email"},{"name":"search_emails","description":"Search emails"},{"name":"read_email","description":"Read a specific email"},{"name":"list_folders","description":"List mail folders"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-email"]""",
            Category = "communication",
            CredentialFieldsJson = """[{"name":"IMAP_HOST","label":"IMAP Host","type":"text","required":true},{"name":"IMAP_USER","label":"Email","type":"text","required":true},{"name":"IMAP_PASSWORD","label":"Password","type":"password","required":true},{"name":"SMTP_HOST","label":"SMTP Host","type":"text","required":true}]""",
            IsBuiltin = true,
        },

        // ── Productivity ────────────────────────────────────────────────

        new()
        {
            Name = "notion",
            Title = "Notion",
            Description = "Search and manage Notion pages, databases, and blocks through the official Notion API. Agents can create and update pages, query databases with filters, manage block content, and search across the entire workspace. Perfect for knowledge management and documentation workflows.",
            Subtitle = "Search, create, and manage pages and databases in Notion",
            AuthorName = "Notion",
            AuthorUrl = "https://notion.so",
            DocumentationUrl = "https://github.com/makenotion/notion-mcp-server",
            RepositoryUrl = "https://github.com/makenotion/notion-mcp-server",
            Logo = BrandfetchLogo("notion.so", "Notion"),
            ToolsJson = """[{"name":"search","description":"Search across Notion workspace"},{"name":"create_page","description":"Create a new page"},{"name":"update_page","description":"Update page properties"},{"name":"query_database","description":"Query a database with filters"},{"name":"get_page","description":"Get page content"},{"name":"create_database","description":"Create a new database"},{"name":"append_blocks","description":"Append content blocks to a page"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@notionhq/notion-mcp-server"]""",
            Category = "productivity",
            CredentialFieldsJson = """[{"name":"OPENAPI_MCP_HEADERS","label":"Integration Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "google-drive",
            Title = "Google Drive",
            Description = "Access, search, and manage files in Google Drive including Docs, Sheets, and Slides. Agents can search for files, read document content, create and update files, manage sharing permissions, and organize folder structures. Supports all Google Workspace file types.",
            Subtitle = "Access and manage files across Google Drive",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("drive.google.com", "Google Drive"),
            ToolsJson = """[{"name":"search_files","description":"Search for files in Drive"},{"name":"read_file","description":"Read file content"},{"name":"create_file","description":"Create a new file"},{"name":"update_file","description":"Update file content"},{"name":"list_files","description":"List files in a folder"},{"name":"share_file","description":"Manage sharing permissions"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-gdrive"]""",
            Category = "productivity",
            CredentialFieldsJson = """[{"name":"GOOGLE_CLIENT_ID","label":"OAuth Client ID","type":"text","required":true},{"name":"GOOGLE_CLIENT_SECRET","label":"OAuth Client Secret","type":"password","required":true},{"name":"GOOGLE_REFRESH_TOKEN","label":"Refresh Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "google-calendar",
            Title = "Google Calendar",
            Description = "Manage Google Calendar events with full CRUD operations. Agents can create, update, and delete events, search for availability, check free/busy status, and manage calendar settings. Supports recurring events, attendee management, and multi-calendar workflows.",
            Subtitle = "Create, update, and search calendar events",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/google-calendar",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("calendar.google.com", "Google Calendar"),
            ToolsJson = """[{"name":"create_event","description":"Create a calendar event"},{"name":"update_event","description":"Update an existing event"},{"name":"delete_event","description":"Delete an event"},{"name":"list_events","description":"List upcoming events"},{"name":"search_events","description":"Search for events"},{"name":"get_freebusy","description":"Check free/busy status"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@anthropic-ai/google-calendar-mcp-server"]""",
            Category = "productivity",
            CredentialFieldsJson = """[{"name":"GOOGLE_CLIENT_ID","label":"OAuth Client ID","type":"text","required":true},{"name":"GOOGLE_CLIENT_SECRET","label":"OAuth Client Secret","type":"password","required":true},{"name":"GOOGLE_REFRESH_TOKEN","label":"Refresh Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "google-maps",
            Title = "Google Maps",
            Description = "Geocoding, directions, place search, and distance calculations powered by Google Maps Platform. Agents can convert addresses to coordinates, calculate routes and travel times, search for nearby places, and get detailed location information. Essential for location-aware applications.",
            Subtitle = "Geocoding, directions, and place search with Google Maps",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("maps.google.com", "Google Maps"),
            ToolsJson = """[{"name":"geocode","description":"Convert address to coordinates"},{"name":"reverse_geocode","description":"Convert coordinates to address"},{"name":"directions","description":"Get directions between locations"},{"name":"search_places","description":"Search for nearby places"},{"name":"place_details","description":"Get detailed place information"},{"name":"distance_matrix","description":"Calculate distances and travel times"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-google-maps"]""",
            Category = "productivity",
            CredentialFieldsJson = """[{"name":"GOOGLE_MAPS_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "todoist",
            Title = "Todoist",
            Description = "Manage Todoist tasks, projects, and labels for personal and team productivity. Agents can create and complete tasks, organize projects, set due dates and priorities, add labels, and track progress. Integrates seamlessly with Todoist's natural language date parsing.",
            Subtitle = "Manage tasks, projects, and priorities in Todoist",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/abhiz123/todoist-mcp-server",
            RepositoryUrl = "https://github.com/abhiz123/todoist-mcp-server",
            Logo = BrandfetchLogo("todoist.com", "Todoist"),
            ToolsJson = """[{"name":"create_task","description":"Create a new task"},{"name":"complete_task","description":"Mark a task as complete"},{"name":"list_tasks","description":"List tasks"},{"name":"update_task","description":"Update a task"},{"name":"list_projects","description":"List projects"},{"name":"create_project","description":"Create a project"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-todoist"]""",
            Category = "productivity",
            CredentialFieldsJson = """[{"name":"TODOIST_API_TOKEN","label":"API Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "airtable",
            Title = "Airtable",
            Description = "Read and manage Airtable bases, tables, and records. Agents can list bases, create and update records, query with filters and sorts, and manage table schemas. Bridges the gap between spreadsheets and databases, making structured data accessible to AI workflows.",
            Subtitle = "Manage bases, tables, and records in Airtable",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/domdomegg/airtable-mcp-server",
            RepositoryUrl = "https://github.com/domdomegg/airtable-mcp-server",
            Logo = BrandfetchLogo("airtable.com", "Airtable"),
            ToolsJson = """[{"name":"list_bases","description":"List Airtable bases"},{"name":"list_records","description":"List records in a table"},{"name":"create_record","description":"Create a new record"},{"name":"update_record","description":"Update a record"},{"name":"get_record","description":"Get a specific record"},{"name":"list_tables","description":"List tables in a base"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-airtable"]""",
            Category = "productivity",
            CredentialFieldsJson = """[{"name":"AIRTABLE_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "trello",
            Title = "Trello",
            Description = "Manage Trello boards, lists, and cards for visual project management. Agents can create and move cards, manage lists, add comments and attachments, assign members, and track board activity. Perfect for kanban-style workflow automation.",
            Subtitle = "Manage boards, lists, and cards for kanban workflows",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/nopalnafiannn/mcp-trello",
            RepositoryUrl = "https://github.com/nopalnafiannn/mcp-trello",
            Logo = BrandfetchLogo("trello.com", "Trello"),
            ToolsJson = """[{"name":"list_boards","description":"List Trello boards"},{"name":"list_cards","description":"List cards in a list"},{"name":"create_card","description":"Create a new card"},{"name":"move_card","description":"Move a card to another list"},{"name":"add_comment","description":"Add a comment to a card"},{"name":"list_lists","description":"List board lists"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-trello"]""",
            Category = "productivity",
            CredentialFieldsJson = """[{"name":"TRELLO_API_KEY","label":"API Key","type":"text","required":true},{"name":"TRELLO_TOKEN","label":"Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "asana",
            Title = "Asana",
            Description = "Manage Asana tasks, projects, and workspaces for team productivity. Agents can create and assign tasks, manage projects and sections, track progress, add comments, and search across workspaces. Supports complex project management workflows with subtasks and dependencies.",
            Subtitle = "Manage tasks, projects, and team workflows in Asana",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/cristip73/asana-mcp-server",
            RepositoryUrl = "https://github.com/cristip73/asana-mcp-server",
            Logo = BrandfetchLogo("asana.com", "Asana"),
            ToolsJson = """[{"name":"create_task","description":"Create a new task"},{"name":"update_task","description":"Update a task"},{"name":"list_tasks","description":"List tasks in a project"},{"name":"list_projects","description":"List projects"},{"name":"add_comment","description":"Add a comment to a task"},{"name":"search_tasks","description":"Search for tasks"},{"name":"list_workspaces","description":"List workspaces"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-asana"]""",
            Category = "productivity",
            CredentialFieldsJson = """[{"name":"ASANA_ACCESS_TOKEN","label":"Access Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },

        // ── Cloud Infrastructure ────────────────────────────────────────

        new()
        {
            Name = "aws",
            Title = "AWS",
            Description = "Core AWS capabilities for managing cloud infrastructure. Agents can interact with S3 buckets, Lambda functions, EC2 instances, CloudWatch logs and metrics, and many other AWS services. Supports IAM-based authentication and works across all AWS regions.",
            Subtitle = "Manage S3, Lambda, EC2, CloudWatch, and more on AWS",
            AuthorName = "AWS Labs",
            AuthorUrl = "https://github.com/awslabs",
            DocumentationUrl = "https://github.com/awslabs/mcp",
            RepositoryUrl = "https://github.com/awslabs/mcp",
            Logo = BrandfetchLogo("aws.amazon.com", "AWS"),
            ToolsJson = """[{"name":"s3_list","description":"List S3 buckets and objects"},{"name":"s3_get","description":"Get an S3 object"},{"name":"s3_put","description":"Upload to S3"},{"name":"lambda_invoke","description":"Invoke a Lambda function"},{"name":"ec2_describe","description":"Describe EC2 instances"},{"name":"cloudwatch_logs","description":"Query CloudWatch logs"},{"name":"cloudwatch_metrics","description":"Get CloudWatch metrics"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@awslabs/mcp-server-core"]""",
            Category = "cloud",
            CredentialFieldsJson = """[{"name":"AWS_ACCESS_KEY_ID","label":"Access Key ID","type":"text","required":true},{"name":"AWS_SECRET_ACCESS_KEY","label":"Secret Access Key","type":"password","required":true},{"name":"AWS_REGION","label":"Region","type":"text","required":false}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "cloudflare",
            Title = "Cloudflare",
            Description = "Manage Cloudflare Workers, KV namespaces, R2 object storage, and D1 databases. Agents can deploy and update Workers scripts, manage edge configuration, interact with storage services, and monitor Cloudflare resources. Enables edge computing automation at scale.",
            Subtitle = "Deploy Workers, manage KV, R2, and D1 on the edge",
            AuthorName = "Cloudflare",
            AuthorUrl = "https://cloudflare.com",
            DocumentationUrl = "https://github.com/cloudflare/mcp-server-cloudflare",
            RepositoryUrl = "https://github.com/cloudflare/mcp-server-cloudflare",
            Logo = BrandfetchLogo("cloudflare.com", "Cloudflare"),
            ToolsJson = """[{"name":"deploy_worker","description":"Deploy a Workers script"},{"name":"list_workers","description":"List deployed Workers"},{"name":"kv_get","description":"Get a KV value"},{"name":"kv_put","description":"Set a KV value"},{"name":"r2_list","description":"List R2 objects"},{"name":"d1_query","description":"Query a D1 database"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@cloudflare/mcp-server-cloudflare"]""",
            Category = "cloud",
            CredentialFieldsJson = """[{"name":"CLOUDFLARE_API_TOKEN","label":"API Token","type":"password","required":true},{"name":"CLOUDFLARE_ACCOUNT_ID","label":"Account ID","type":"text","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "vercel",
            Title = "Vercel",
            Description = "Manage Vercel deployments, projects, and domains for frontend and full-stack applications. Agents can trigger deployments, view build logs, manage environment variables, configure domains, and monitor project status. Streamlines the deployment lifecycle for modern web applications.",
            Subtitle = "Deploy, manage, and monitor projects on Vercel",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/Quegenx/vercel-mcp-server",
            RepositoryUrl = "https://github.com/Quegenx/vercel-mcp-server",
            Logo = BrandfetchLogo("vercel.com", "Vercel"),
            ToolsJson = """[{"name":"list_deployments","description":"List deployments"},{"name":"create_deployment","description":"Trigger a deployment"},{"name":"list_projects","description":"List projects"},{"name":"get_deployment","description":"Get deployment details"},{"name":"list_domains","description":"List domains"},{"name":"set_env_var","description":"Set an environment variable"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-vercel"]""",
            Category = "cloud",
            CredentialFieldsJson = """[{"name":"VERCEL_API_TOKEN","label":"API Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "kubernetes",
            Title = "Kubernetes",
            Description = "Manage Kubernetes clusters including pods, deployments, services, and logs. Agents can list and describe resources, view pod logs, scale deployments, apply manifests, and troubleshoot cluster issues. Uses the local kubeconfig for authentication and supports multiple cluster contexts.",
            Subtitle = "Manage pods, deployments, services, and logs in K8s clusters",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/Flux159/mcp-server-kubernetes",
            RepositoryUrl = "https://github.com/Flux159/mcp-server-kubernetes",
            Logo = BrandfetchLogo("kubernetes.io", "Kubernetes"),
            ToolsJson = """[{"name":"list_pods","description":"List pods in a namespace"},{"name":"get_pod_logs","description":"Get pod logs"},{"name":"list_deployments","description":"List deployments"},{"name":"scale_deployment","description":"Scale a deployment"},{"name":"apply_manifest","description":"Apply a YAML manifest"},{"name":"describe_resource","description":"Describe a Kubernetes resource"},{"name":"list_services","description":"List services"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-kubernetes"]""",
            Category = "cloud",
            IsBuiltin = true,
        },
        new()
        {
            Name = "terraform",
            Title = "Terraform",
            Description = "Manage Terraform infrastructure-as-code configurations, plans, and state. Agents can initialize workspaces, create execution plans, apply changes, inspect state, and manage modules. Supports both local execution and Terraform Cloud integration for team workflows.",
            Subtitle = "Plan, apply, and manage infrastructure as code",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/Azure/terraform-mcp-server",
            RepositoryUrl = "https://github.com/Azure/terraform-mcp-server",
            Logo = BrandfetchLogo("terraform.io", "Terraform"),
            ToolsJson = """[{"name":"init","description":"Initialize Terraform workspace"},{"name":"plan","description":"Create an execution plan"},{"name":"apply","description":"Apply changes"},{"name":"show_state","description":"Show current state"},{"name":"list_resources","description":"List managed resources"},{"name":"validate","description":"Validate configuration"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-terraform"]""",
            Category = "cloud",
            IsBuiltin = true,
        },
        new()
        {
            Name = "docker",
            Title = "Docker",
            Description = "Manage Docker containers, images, volumes, and networks. Agents can list and inspect containers, pull and build images, manage volumes, view container logs, and execute commands inside running containers. Simplifies container management and debugging workflows.",
            Subtitle = "Manage containers, images, and volumes with Docker",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/ckreiling/mcp-server-docker",
            RepositoryUrl = "https://github.com/ckreiling/mcp-server-docker",
            Logo = BrandfetchLogo("docker.com", "Docker"),
            ToolsJson = """[{"name":"list_containers","description":"List Docker containers"},{"name":"inspect_container","description":"Inspect a container"},{"name":"container_logs","description":"View container logs"},{"name":"list_images","description":"List Docker images"},{"name":"pull_image","description":"Pull an image"},{"name":"exec_command","description":"Execute command in a container"},{"name":"list_volumes","description":"List volumes"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-docker"]""",
            Category = "cloud",
            IsBuiltin = true,
        },

        // ── Monitoring & Observability ───────────────────────────────────

        new()
        {
            Name = "grafana",
            Title = "Grafana",
            Description = "Query Grafana dashboards, datasources, and alerts for monitoring and observability. Agents can search dashboards, query Prometheus and other datasources, list and manage alert rules, and access annotation data. Helps with incident response and performance monitoring.",
            Subtitle = "Query dashboards, datasources, and alerts in Grafana",
            AuthorName = "Grafana Labs",
            AuthorUrl = "https://grafana.com",
            DocumentationUrl = "https://github.com/grafana/mcp-grafana",
            RepositoryUrl = "https://github.com/grafana/mcp-grafana",
            Logo = BrandfetchLogo("grafana.com", "Grafana"),
            ToolsJson = """[{"name":"search_dashboards","description":"Search Grafana dashboards"},{"name":"query_datasource","description":"Query a datasource"},{"name":"list_alerts","description":"List alert rules"},{"name":"get_dashboard","description":"Get dashboard details"},{"name":"list_datasources","description":"List datasources"},{"name":"get_annotations","description":"Get annotations"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@grafana/mcp-grafana"]""",
            Category = "monitoring",
            CredentialFieldsJson = """[{"name":"GRAFANA_URL","label":"Grafana URL","type":"text","required":true},{"name":"GRAFANA_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "datadog",
            Title = "Datadog",
            Description = "Query Datadog metrics, logs, and monitors for infrastructure and application observability. Agents can search logs, query metric timeseries, list and manage monitors, view dashboards, and check service health. Essential for monitoring complex distributed systems.",
            Subtitle = "Query metrics, logs, and monitors from Datadog",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/GeLi2001/datadog-mcp",
            RepositoryUrl = "https://github.com/GeLi2001/datadog-mcp",
            Logo = BrandfetchLogo("datadoghq.com", "Datadog"),
            ToolsJson = """[{"name":"search_logs","description":"Search Datadog logs"},{"name":"query_metrics","description":"Query metric timeseries"},{"name":"list_monitors","description":"List monitors"},{"name":"get_monitor","description":"Get monitor details"},{"name":"list_dashboards","description":"List dashboards"},{"name":"mute_monitor","description":"Mute a monitor"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-datadog"]""",
            Category = "monitoring",
            CredentialFieldsJson = """[{"name":"DD_API_KEY","label":"API Key","type":"password","required":true},{"name":"DD_APP_KEY","label":"Application Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "pagerduty",
            Title = "PagerDuty",
            Description = "Manage PagerDuty incidents, services, and on-call schedules for incident response. Agents can create and acknowledge incidents, view on-call rotations, list services, and manage escalation policies. Streamlines incident management and reduces mean time to resolution.",
            Subtitle = "Manage incidents, on-call schedules, and escalations",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/wparsons-heap/pagerduty-mcp-server",
            RepositoryUrl = "https://github.com/wparsons-heap/pagerduty-mcp-server",
            Logo = BrandfetchLogo("pagerduty.com", "PagerDuty"),
            ToolsJson = """[{"name":"list_incidents","description":"List incidents"},{"name":"create_incident","description":"Create an incident"},{"name":"acknowledge_incident","description":"Acknowledge an incident"},{"name":"resolve_incident","description":"Resolve an incident"},{"name":"list_services","description":"List services"},{"name":"get_oncall","description":"Get on-call schedule"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-pagerduty"]""",
            Category = "monitoring",
            CredentialFieldsJson = """[{"name":"PAGERDUTY_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },

        // ── Finance & Payments ──────────────────────────────────────────

        new()
        {
            Name = "stripe",
            Title = "Stripe",
            Description = "Manage Stripe payments, customers, subscriptions, and invoices through the official Stripe Agent Toolkit. Agents can create payment intents, manage customer records, handle subscriptions, generate invoices, and query transaction history. Built and maintained by Stripe for reliable payment automation.",
            Subtitle = "Process payments, manage subscriptions, and handle invoices",
            AuthorName = "Stripe",
            AuthorUrl = "https://stripe.com",
            DocumentationUrl = "https://github.com/stripe/agent-toolkit",
            RepositoryUrl = "https://github.com/stripe/agent-toolkit",
            Logo = BrandfetchLogo("stripe.com", "Stripe"),
            ToolsJson = """[{"name":"create_payment_intent","description":"Create a payment intent"},{"name":"list_customers","description":"List customers"},{"name":"create_customer","description":"Create a customer"},{"name":"create_subscription","description":"Create a subscription"},{"name":"list_invoices","description":"List invoices"},{"name":"create_invoice","description":"Create an invoice"},{"name":"list_charges","description":"List charges"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@stripe/mcp@latest"]""",
            Category = "finance",
            CredentialFieldsJson = """[{"name":"STRIPE_SECRET_KEY","label":"Secret Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "paypal",
            Title = "PayPal",
            Description = "Manage PayPal transactions, invoices, and payment links through the official PayPal Agent Toolkit. Agents can create and send invoices, generate payment links, query transaction history, and manage disputes. Supports both sandbox and live environments for development and production.",
            Subtitle = "Create invoices, payment links, and manage transactions",
            AuthorName = "PayPal",
            AuthorUrl = "https://paypal.com",
            DocumentationUrl = "https://github.com/paypal/agent-toolkit",
            RepositoryUrl = "https://github.com/paypal/agent-toolkit",
            Logo = BrandfetchLogo("paypal.com", "PayPal"),
            ToolsJson = """[{"name":"create_invoice","description":"Create a PayPal invoice"},{"name":"send_invoice","description":"Send an invoice"},{"name":"create_payment_link","description":"Create a payment link"},{"name":"list_transactions","description":"List transactions"},{"name":"get_transaction","description":"Get transaction details"},{"name":"manage_disputes","description":"Manage payment disputes"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@paypal/mcp@latest"]""",
            Category = "finance",
            CredentialFieldsJson = """[{"name":"PAYPAL_CLIENT_ID","label":"Client ID","type":"text","required":true},{"name":"PAYPAL_CLIENT_SECRET","label":"Client Secret","type":"password","required":true}]""",
            IsBuiltin = true,
        },

        // ── CRM & Sales ─────────────────────────────────────────────────

        new()
        {
            Name = "hubspot",
            Title = "HubSpot",
            Description = "Manage HubSpot CRM contacts, deals, companies, and tickets. Agents can create and update records, search across CRM objects, manage deal pipelines, and track customer interactions. Enables sales automation, lead management, and customer relationship workflows.",
            Subtitle = "Manage contacts, deals, and pipelines in HubSpot CRM",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/buzbuz55/hubspot-mcp-server",
            RepositoryUrl = "https://github.com/buzbuz55/hubspot-mcp-server",
            Logo = BrandfetchLogo("hubspot.com", "HubSpot"),
            ToolsJson = """[{"name":"create_contact","description":"Create a contact"},{"name":"update_contact","description":"Update a contact"},{"name":"search_contacts","description":"Search contacts"},{"name":"create_deal","description":"Create a deal"},{"name":"list_deals","description":"List deals"},{"name":"create_company","description":"Create a company"},{"name":"create_ticket","description":"Create a support ticket"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-hubspot"]""",
            Category = "crm",
            CredentialFieldsJson = """[{"name":"HUBSPOT_ACCESS_TOKEN","label":"Access Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "salesforce",
            Title = "Salesforce",
            Description = "Query and manage Salesforce CRM objects, reports, and dashboards using SOQL. Agents can search accounts, contacts, and opportunities, create and update records, run reports, and access Salesforce metadata. Supports any Salesforce org with standard API access.",
            Subtitle = "Query and manage CRM objects with SOQL in Salesforce",
            AuthorName = "Community",
            AuthorUrl = "",
            DocumentationUrl = "https://github.com/smn-cln/salesforce-mcp",
            RepositoryUrl = "https://github.com/smn-cln/salesforce-mcp",
            Logo = BrandfetchLogo("salesforce.com", "Salesforce"),
            ToolsJson = """[{"name":"soql_query","description":"Run a SOQL query"},{"name":"create_record","description":"Create a Salesforce record"},{"name":"update_record","description":"Update a record"},{"name":"get_record","description":"Get a record by ID"},{"name":"search","description":"Search across objects"},{"name":"describe_object","description":"Describe an object schema"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","mcp-server-salesforce"]""",
            Category = "crm",
            CredentialFieldsJson = """[{"name":"SALESFORCE_INSTANCE_URL","label":"Instance URL","type":"text","required":true},{"name":"SALESFORCE_ACCESS_TOKEN","label":"Access Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },

        // ── AI & Knowledge ──────────────────────────────────────────────

        new()
        {
            Name = "memory",
            Title = "Memory",
            Description = "Knowledge graph-based persistent memory for LLMs. Agents can create entities, define relationships, and add observations to build a structured knowledge base that persists across conversations. Enables long-term memory, context accumulation, and knowledge retrieval using graph traversal.",
            Subtitle = "Persistent knowledge graph memory for AI agents",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("modelcontextprotocol.io", "Memory"),
            ToolsJson = """[{"name":"create_entities","description":"Create entities in the knowledge graph"},{"name":"create_relations","description":"Create relationships between entities"},{"name":"add_observations","description":"Add observations to entities"},{"name":"delete_entities","description":"Delete entities"},{"name":"delete_observations","description":"Delete observations"},{"name":"delete_relations","description":"Delete relationships"},{"name":"read_graph","description":"Read the entire knowledge graph"},{"name":"search_nodes","description":"Search for nodes"},{"name":"open_nodes","description":"Open specific nodes"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-memory"]""",
            Category = "ai",
            IsBuiltin = true,
        },
        new()
        {
            Name = "sequential-thinking",
            Title = "Sequential Thinking",
            Description = "Dynamic and reflective problem-solving through structured thought sequences. Agents can break down complex problems into sequential steps, revise their thinking, branch into alternative approaches, and build toward well-reasoned conclusions. Ideal for multi-step reasoning, planning, and analysis tasks.",
            Subtitle = "Structured step-by-step reasoning for complex problems",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("modelcontextprotocol.io", "Sequential Thinking"),
            ToolsJson = """[{"name":"sequentialthinking","description":"Process a thought in a sequential chain"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-sequentialthinking"]""",
            Category = "ai",
            IsBuiltin = true,
        },
        new()
        {
            Name = "context7",
            Title = "Context7",
            Description = "Up-to-date documentation for any library directly in your AI prompts. Context7 indexes and serves current documentation, examples, and API references for thousands of open-source libraries. Agents get accurate, version-specific answers instead of relying on potentially outdated training data.",
            Subtitle = "Live library documentation and API references for AI prompts",
            AuthorName = "Upstash",
            AuthorUrl = "https://upstash.com",
            DocumentationUrl = "https://github.com/upstash/context7",
            RepositoryUrl = "https://github.com/upstash/context7",
            Logo = BrandfetchLogo("context7.com", "Context7"),
            ToolsJson = """[{"name":"resolve_library","description":"Resolve a library name to Context7 ID"},{"name":"get_library_docs","description":"Get documentation for a library"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@upstash/context7-mcp@latest"]""",
            Category = "ai",
            IsBuiltin = true,
        },

        // ── CI/CD & DevOps ──────────────────────────────────────────────

        new()
        {
            Name = "circleci",
            Title = "CircleCI",
            Description = "Analyze and fix CircleCI pipeline failures with intelligent debugging. Agents can view pipeline status, get build logs, analyze test failures, and suggest fixes. Reduces mean time to resolution by surfacing relevant failure context directly in the conversation.",
            Subtitle = "Analyze pipeline failures and debug CI builds",
            AuthorName = "CircleCI",
            AuthorUrl = "https://circleci.com",
            DocumentationUrl = "https://github.com/CircleCI-Public/mcp-server-circleci",
            RepositoryUrl = "https://github.com/CircleCI-Public/mcp-server-circleci",
            Logo = BrandfetchLogo("circleci.com", "CircleCI"),
            ToolsJson = """[{"name":"get_pipeline","description":"Get pipeline details"},{"name":"list_pipelines","description":"List pipelines"},{"name":"get_job_logs","description":"Get job logs"},{"name":"list_workflows","description":"List workflows"},{"name":"get_test_results","description":"Get test results"},{"name":"retry_workflow","description":"Retry a failed workflow"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@circleci/mcp-server-circleci"]""",
            Category = "devops",
            CredentialFieldsJson = """[{"name":"CIRCLECI_TOKEN","label":"API Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "buildkite",
            Title = "Buildkite",
            Description = "Manage Buildkite CI/CD pipelines, builds, and agents. Agents can trigger builds, view build logs, manage pipeline configurations, monitor agent pools, and track build status. Designed for teams running builds on their own infrastructure with Buildkite orchestration.",
            Subtitle = "Trigger builds, view logs, and manage CI/CD pipelines",
            AuthorName = "Buildkite",
            AuthorUrl = "https://buildkite.com",
            DocumentationUrl = "https://github.com/buildkite/buildkite-mcp-server",
            RepositoryUrl = "https://github.com/buildkite/buildkite-mcp-server",
            Logo = BrandfetchLogo("buildkite.com", "Buildkite"),
            ToolsJson = """[{"name":"trigger_build","description":"Trigger a new build"},{"name":"list_builds","description":"List builds"},{"name":"get_build","description":"Get build details"},{"name":"get_build_log","description":"Get build log output"},{"name":"list_pipelines","description":"List pipelines"},{"name":"list_agents","description":"List build agents"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@buildkite/mcp-server"]""",
            Category = "devops",
            CredentialFieldsJson = """[{"name":"BUILDKITE_API_TOKEN","label":"API Token","type":"password","required":true}]""",
            IsBuiltin = true,
        },

        // ── Utilities ───────────────────────────────────────────────────

        new()
        {
            Name = "time",
            Title = "Time",
            Description = "Time and timezone conversion utilities for working with dates, times, and timezones. Agents can get the current time in any timezone, convert between timezones, and perform time calculations. Essential for scheduling, coordination, and time-aware workflows across global teams.",
            Subtitle = "Get current time and convert between timezones",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("modelcontextprotocol.io", "Time"),
            ToolsJson = """[{"name":"get_current_time","description":"Get current time in a timezone"},{"name":"convert_time","description":"Convert time between timezones"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-time"]""",
            Category = "utility",
            IsBuiltin = true,
        },
        new()
        {
            Name = "e2b",
            Title = "E2B Code Sandbox",
            Description = "Execute code in secure cloud sandboxes powered by E2B. Agents can run Python, JavaScript, TypeScript, and other languages in isolated environments with full network access. Supports package installation, file operations, and long-running processes. Ideal for data analysis, code generation testing, and computational tasks.",
            Subtitle = "Execute code safely in isolated cloud sandboxes",
            AuthorName = "E2B",
            AuthorUrl = "https://e2b.dev",
            DocumentationUrl = "https://github.com/e2b-dev/mcp-server",
            RepositoryUrl = "https://github.com/e2b-dev/mcp-server",
            Logo = BrandfetchLogo("e2b.dev", "E2B Code Sandbox"),
            ToolsJson = """[{"name":"run_code","description":"Execute code in a sandbox"},{"name":"install_packages","description":"Install packages in sandbox"},{"name":"read_file","description":"Read a file from sandbox"},{"name":"write_file","description":"Write a file to sandbox"},{"name":"list_files","description":"List files in sandbox"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@e2b/mcp-server"]""",
            Category = "utility",
            CredentialFieldsJson = """[{"name":"E2B_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "elevenlabs",
            Title = "ElevenLabs",
            Description = "Text-to-speech synthesis with natural-sounding AI voices from ElevenLabs. Agents can generate speech from text, clone voices, manage voice libraries, and create audio content. Supports multiple languages, voice styles, and fine-tuned pronunciation for professional audio production.",
            Subtitle = "Generate natural speech with AI voice synthesis",
            AuthorName = "ElevenLabs",
            AuthorUrl = "https://elevenlabs.io",
            DocumentationUrl = "https://github.com/elevenlabs/elevenlabs-mcp",
            RepositoryUrl = "https://github.com/elevenlabs/elevenlabs-mcp",
            Logo = BrandfetchLogo("elevenlabs.io", "ElevenLabs"),
            ToolsJson = """[{"name":"text_to_speech","description":"Convert text to speech"},{"name":"list_voices","description":"List available voices"},{"name":"get_voice","description":"Get voice details"},{"name":"clone_voice","description":"Clone a voice from audio samples"},{"name":"generate_audio","description":"Generate audio with settings"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@elevenlabs/mcp-server"]""",
            Category = "utility",
            CredentialFieldsJson = """[{"name":"ELEVENLABS_API_KEY","label":"API Key","type":"password","required":true}]""",
            IsBuiltin = true,
        },
        new()
        {
            Name = "puppeteer",
            Title = "Puppeteer",
            Description = "Browser automation with Google Puppeteer for navigating pages, taking screenshots, clicking elements, filling forms, and executing JavaScript. Provides headless Chrome control for web scraping, testing, and interactive web workflows. Lightweight alternative to Playwright for Chromium-only use cases.",
            Subtitle = "Automate Chrome for screenshots, scraping, and testing",
            AuthorName = "Anthropic",
            AuthorUrl = "https://github.com/modelcontextprotocol",
            DocumentationUrl = "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
            RepositoryUrl = "https://github.com/modelcontextprotocol/servers",
            Logo = BrandfetchLogo("pptr.dev", "Puppeteer"),
            ToolsJson = """[{"name":"navigate","description":"Navigate to a URL"},{"name":"screenshot","description":"Take a screenshot"},{"name":"click","description":"Click an element"},{"name":"fill","description":"Fill in a form field"},{"name":"select","description":"Select a dropdown option"},{"name":"hover","description":"Hover over an element"},{"name":"evaluate","description":"Execute JavaScript in the page"}]""",
            TransportType = McpTransportType.Stdio,
            Command = "npx",
            Args = """["-y","@modelcontextprotocol/server-puppeteer"]""",
            Category = "utility",
            IsBuiltin = true,
        },
    ];
}
